import type { Metadata } from "next";
import { montserrat } from "./ui/fonts";
import { PlayerProvider } from '@/context/PlayerContext';
import "./globals.css";
import Sidenav from "./ui/sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <PlayerProvider>
          <div className="flex h-screen">
            <Sidenav/>
            <div className="w-full">
              {children}
            </div>
          </div>
        </PlayerProvider>
      </body>
    </html>
  );
}
